CREATE DATABASE SCH_PORTAL_VAGAS;
CREATE TABLE IF NOT EXISTS SCH_PORTAL_VAGAS.JOB (

    ID INT GENERATED ALWAYS AS IDENTITY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    COMPANY TEXT NOT NULL,
    PUBLISH_DATE DATE NOT NULL,
    EXPIRE_DATE DATE NOT NULL,
    EXPERTISE_LEVEL TEXT NOT NULL,
    TYPE_OF_JOB TEXT NOT NULL,
    TEMPORARY BOOLEAN NOT NULL,
    ACCEPT_PCD BOOLEAN NOT NULL,
    STATE INT NOT NULL,
    CITY TEXT NOT NULL,
    LOCATION TEXT NOT NULL,

    CONSTRAINT ID_JOB_PK PRIMARY KEY (ID)

);

CREATE TABLE IF NOT EXISTS SCH_PORTAL_VAGAS.USER (

    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,

    CONSTRAINT ID_USER_PK PRIMARY KEY (ID)

);

CREATE TABLE IF NOT EXISTS SCH_PORTAL_VAGAS.PERMISSION_LEVEL (

    ID INT GENERATED ALWAYS AS IDENTITY,
    ID_USER INT NOT NULL,
    PERMISSION_LEVEL INT NOT NULL,

    CONSTRAINT ID_PER_LEVEL_PK PRIMARY KEY (ID),
    CONSTRAINT ID_USER_FK FOREIGN KEY (ID_USER) REFERENCES SCH_PORTAL_VAGAS.JOB(ID)

);