services:
  db:
    container_name: db_portal_vagas
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
